apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: foobar
spec:
  kafkaClusterRef:
    name: kafka
    namespace: production
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: mds-client
    endpoint: https://kafka.production.svc.cluster.local:8090
